import React from 'react';
import { Voicing } from '../logic/voicing-generator';
import { validateSequence } from '../logic/persistence-utils';
import { Play, Square, Trash2, X, Download, Upload } from 'lucide-react';
import ChordDiagram from './ChordDiagram';

interface SequencerProps {
    sequence: ((Voicing & { intervalMap?: Record<string, string> }) | null)[];
    activeSlot: number | null;
    currentBeat: number;
    isPlaying: boolean;
    bpm: number;
    onBpmChange: (bpm: number) => void;
    onSlotClick: (index: number) => void;
    onClearSlot: (index: number, e: React.MouseEvent) => void;
    onPlay: () => void;
    onStop: () => void;
    onClearAll: () => void;
    onLoad: (seq: any[]) => void;
    displayMode: 'notes' | 'intervals';
    intervalMap: Record<string, string>;
}

const Sequencer: React.FC<SequencerProps> = ({
    sequence,
    activeSlot,
    currentBeat,
    isPlaying,
    bpm,
    onBpmChange,
    onSlotClick,
    onClearSlot,
    onPlay,
    onStop,
    onClearAll,
    onLoad,
    displayMode,
    intervalMap
}) => {
    // Local state for input to allow typing without immediate clamping
    const [localBpm, setLocalBpm] = React.useState(bpm.toString());

    // Sync local state when prop changes (e.g. if set externally)
    React.useEffect(() => {
        setLocalBpm(bpm.toString());
    }, [bpm]);

    const handleBpmCommit = () => {
        let val = parseInt(localBpm);
        if (isNaN(val)) val = 90; // Default fallback
        const clamped = Math.min(160, Math.max(40, val));
        setLocalBpm(clamped.toString());
        onBpmChange(clamped);
    };

    const handleSave = () => {
        let filename = window.prompt('Enter filename for sequence:', 'sequence');
        if (!filename) return; // User cancelled or empty

        if (!filename.endsWith('.json')) {
            filename += '.json';
        }

        const dataStr = JSON.stringify(sequence);
        const blob = new Blob([dataStr], { type: 'application/json' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = filename;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    };


    const handleLoad = (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0];
        if (!file) return;

        const reader = new FileReader();
        reader.onload = (event) => {
            try {
                const json = JSON.parse(event.target?.result as string);
                if (validateSequence(json)) {
                    onLoad(json);
                } else {
                    alert('Invalid sequence file. Please select a valid JSON file generated by this application.');
                }
            } catch (err) {
                console.error('Failed to parse sequence file', err);
                alert('Failed to parse sequence file. It might be corrupted or not a valid JSON.');
            }
        };
        reader.readAsText(file);
        // Reset input so same file can be selected again
        e.target.value = '';
    };

    return (
        <details className="sequencer-details group">
            <summary className="sequencer-summary">
                <span>Chord Sequencer</span>
            </summary>

            <div className="px-6 pb-6 fade-in-up">
                <div className="sequencer-controls">
                    <div className="bpm-input-container" onClick={() => document.getElementById('bpm-input')?.focus()}>
                        <label htmlFor="bpm-input" className="bpm-label">Tempo (bpm)</label>
                        <input
                            id="bpm-input"
                            type="number"
                            min="40"
                            max="160"
                            value={localBpm}
                            onChange={(e) => setLocalBpm(e.target.value)}
                            onBlur={handleBpmCommit}
                            onKeyDown={(e) => {
                                if (e.key === 'Enter') {
                                    handleBpmCommit();
                                    (e.target as HTMLInputElement).blur();
                                }
                            }}
                            className="bpm-input"
                        />
                    </div>
                    <button
                        onClick={isPlaying ? onStop : onPlay}
                        className={`control-btn ${isPlaying ? 'btn-stop' : 'btn-play'}`}
                    >
                        {isPlaying ? <><Square size={18} /> Stop</> : <><Play size={18} /> Play</>}
                    </button>
                    <button
                        onClick={onClearAll}
                        className="control-btn btn-clear"
                        title="Clear Sequence"
                    >
                        <Trash2 size={18} /> Clear
                    </button>

                    <div className="h-6 w-px bg-gray-700 mx-2"></div>

                    <button
                        onClick={handleSave}
                        className="control-btn btn-clear"
                        title="Save Sequence"
                    >
                        <Download size={18} /> Save
                    </button>
                    <button
                        onClick={() => document.getElementById('hidden-file-input')?.click()}
                        className="control-btn btn-clear"
                    >
                        <Upload size={18} /> Load
                    </button>
                    <input
                        id="hidden-file-input"
                        type="file"
                        accept=".json"
                        onChange={handleLoad}
                        style={{ display: 'none' }}
                    />
                </div>


                {isPlaying ? (
                    <div className="sequencer-playback-view">
                        {/* Playback View - Measure/Beat Indicator */}
                        <div style={{ fontSize: '1.8rem', textAlign: 'center', marginBottom: '1rem', color: 'var(--text-color)', fontWeight: 'bold' }}>
                            Measure {Math.floor(currentBeat / 4) + 1} : Beat {(currentBeat % 4) + 1}
                        </div>

                        <div
                            className="inline-block"
                            style={{ width: 'max-content', margin: '0 auto', marginTop: '0.5rem' }}
                        >
                            <ChordDiagram
                                voicing={sequence[currentBeat]}
                                displayMode={displayMode}
                                intervalMap={sequence[currentBeat]?.intervalMap || intervalMap}
                                onClick={undefined}
                                interactive={false}
                            />
                        </div>
                    </div>
                ) : (
                    <div className="sequencer-scroll-container">
                        {/* 40 Measures (was 8) */}
                        {Array.from({ length: 40 }, (_, i) => i).map(measureIdx => (
                            <div key={measureIdx} className="sequencer-measure-card">
                                <div className="measure-label">Measure {measureIdx + 1}</div>
                                <div className="beat-grid">
                                    {[0, 1, 2, 3].map(beatIdx => {
                                        const globalIdx = measureIdx * 4 + beatIdx;
                                        const voicing = sequence[globalIdx];
                                        const isActive = activeSlot === globalIdx;

                                        return (
                                            <div
                                                key={globalIdx}
                                                onClick={() => onSlotClick(globalIdx)}
                                                className={`beat-slot ${isActive ? 'active' : ''} ${voicing ? 'occupied' : ''}`}
                                            >
                                                <div className="beat-slot-content">
                                                    {isActive && (
                                                        <span className="play-cursor">►</span>
                                                    )}

                                                    <div className="beat-text-wrapper">
                                                        <span className="beat-label-mini">Beat {beatIdx + 1}</span>
                                                        {voicing && (
                                                            <div style={{ minWidth: 0, textAlign: 'left', overflow: 'hidden' }}>
                                                                <span className="chord-name-text">{voicing.name}</span>
                                                            </div>
                                                        )}
                                                    </div>

                                                    {voicing && (
                                                        <button
                                                            onClick={(e) => onClearSlot(globalIdx, e)}
                                                            className="slot-clear-btn"
                                                        >
                                                            <X size={10} />
                                                        </button>
                                                    )}
                                                </div>
                                            </div>
                                        );
                                    })}
                                </div>
                            </div>
                        ))}
                    </div>
                )}

                {!isPlaying && (
                    <div style={{ marginTop: '1rem', color: '#6b7280', fontSize: '0.875rem', textAlign: 'center' }}>
                        <p>Click a beat to select it, then click a chord diagram below to add it to the sequence.</p>
                    </div>
                )}
            </div>
        </details >
    );
};

export default Sequencer;
